### ISSUE TITLE
UART communication not working - raspberry Pi Radio Bridge

### ISSUE THREAD

**Issue by earlthesquirrel** [canique/gateway#2]
After upgrading and then running your install script, when I start up, I see the following failure:

Mar 18 23:22:34 caniquepi systemd[1]: Started Canique Radio Bridge.
Mar 18 23:22:36 caniquepi python[584]: RSSI threshold -98
Mar 18 23:22:36 caniquepi python[584]: Hard resetting Gateway Hat
Mar 18 23:22:36 caniquepi python[584]: Dropped root privileges
Mar 18 23:22:36 caniquepi python[584]: user ID real/effective/saved (112, 112, 112)
Mar 18 23:22:36 caniquepi python[584]: Suppl. groups [20], effective group 995, real group 995
Mar 18 23:22:42 caniquepi python[584]: Timed out waiting for Radio Hat to start up. Is Radio Hat connected? Exiting.
Mar 18 23:22:42 caniquepi systemd[1]: canique-radio-bridge.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Mar 18 23:22:42 caniquepi systemd[1]: canique-radio-bridge.service: Failed with result 'exit-code'.
Mar 18 23:22:42 caniquepi systemd[1]: canique-radio-bridge.service: Consumed 1.436s CPU time.

The radio board lights do flash, but at this point, I'm blocked.

I've tried 3 times with a clean OS install on the SD card.... just no luck.

**Comment by canique** [comment]
The error indicates that something with the UART connection between Raspberry and Hat is wrong.
The radio RX/TX leds flash simultaenously when the reset pin of the hat is pulled low and the hat is running its bootloader to start up. This is normal when the service canique-radio-bridge is started - it first resets the hat.

Your hat has been tested successfully on a Raspberry 4. So let's find out whether there is a connection error or a software error.

Which Raspberry image are you using? And which Raspberry hardware version?
Is it a 32 Bit or 64 Bit image?
Do you get any errors during the installation?

Does a shutdown of the Raspberry and a reboot fix the issue? (After the installation procedure, the Raspberry must be rebooted once)
How is the hat connected to the Raspberry? Is it attached on it? Connected via cable?

How do you install the OS on the SD card?

**Comment by canique** [comment]
During the installation you should read something like:
"Using UART interface uart1"

If you run `cat /boot/config.txt` there should be a line "enable_uart=1"

If you run `cat /boot/cmdline.txt` it should read something like:
console=tty1 root=/dev/mmcblkXXXX rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

**Comment by earlthesquirrel** [comment]
- It's a 32 bit install (made sure to do that).
- No errors after fixing influx issue.
- enable_uart=1 is present.  Last line.
- My cmdline.txt file has this : console=tty1 root=PARTUUID=96767b56-02 rootfstype=ext4 fsck.repair=yes rootwait

Just re-did install (for influx) and still get the following: 

canique-radio-bridge.service - Canique Radio Bridge
     Loaded: loaded (/lib/systemd/system/canique-radio-bridge.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-03-20 14:08:48 EDT; 4s ago
    Process: 913 ExecStart=/opt/venvs/canique-radio-bridge/bin/python -u /opt/venvs/canique-radio-bridge/bin/startRadioBridge.py --networkId >
   Main PID: 913 (code=exited, status=3)
        CPU: 1.144s

Mar 20 14:08:41 caniquepi systemd[1]: Started Canique Radio Bridge.
Mar 20 14:08:42 caniquepi python[913]: RSSI threshold -98
Mar 20 14:08:42 caniquepi python[913]: Hard resetting Gateway Hat
Mar 20 14:08:42 caniquepi python[913]: Dropped root privileges
Mar 20 14:08:42 caniquepi python[913]: user ID real/effective/saved (112, 112, 112)
Mar 20 14:08:42 caniquepi python[913]: Suppl. groups [20], effective group 995, real group 995
Mar 20 14:08:48 caniquepi python[913]: Timed out waiting for Radio Hat to start up. Is Radio Hat connected? Exiting.
Mar 20 14:08:48 caniquepi systemd[1]: canique-radio-bridge.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Mar 20 14:08:48 caniquepi systemd[1]: canique-radio-bridge.service: Failed with result 'exit-code'.
Mar 20 14:08:48 caniquepi systemd[1]: canique-radio-bridge.service: Consumed 1.144s CPU time.


When I do _sudo systemctl restart canique-radio-bridge_ I do see the two lights flash on the radio board... 
Any other ideas?   Should I try this with either a 64 bit install or on a Raspberry Pi 4?

**Comment by canique** [comment]
64 bit won't work - the binaries do not support 64 bit.

You can try it on a Raspberry Pi 4.
I do have a Raspberry Pi 3 myself, and will retest it there tomorrow with a fresh SD card.

For now, make sure you're using "Raspberry Pi OS Lite". This is the operating system it has been tested against.

What you can try is, shutdown, unplug power to the Raspberry, wait, and then reconnect power. UART needs one reboot cycle of the whole operating system to get activated.

Also worth noting: I'm assuming there is nothing else connected to the Raspberry, especially no  other hat, occupying the UART pins.

**Comment by canique** [comment]
You can also send a picture of the hardware setup if you want. Especially the hat on the Raspberry (viewed from the side). Maybe I'll notice something - like connector not fully plugged in...

**Comment by earlthesquirrel** [comment]
I did use Raspberry Pi OS Lite -- made sure of that.
I have been unplugging the board after the shutdown.   
Here's a picture
![IMG_0620](https://user-images.githubusercontent.com/4523243/226440980-db90d920-2ead-423e-9203-571d9fe98d42.jpeg)

**Comment by earlthesquirrel** [comment]
BTW, I was checking, this board is a 3B +, I have a 3B handy... only have Compute in a Pi carrier board for 4 handy....
Thanks for the pointers so far!  :-)

I'm also waiting to see how the low energy contest goes, definitely want to work with you on some potential versions to help with rain gauge with hall sensor :-)

**Comment by earlthesquirrel** [comment]
FYI -- Swapped out the 3B+ for a 3B.  Now the service seems to start ok.

**Comment by canique** [comment]
Ok, the 3B+ should have faster network, faster CPU, etc. but nothing that should break the code.

Maybe the serial port device is different.
What does the cmd `ls -l /dev/serial*` display?

You can try 
`sudo nano /etc/cnq-radio-bridge`
and then change
`[UART]

device=/dev/serial0
`

to 
`[UART]

device=/dev/serial1
`

then save the file and restart canique-radio-bridge service.

**Comment by canique** [comment]
My Raspberry 3 is a 3B. So on a 3B it's working fine, like on yours.
If you cannot get it to run on a 3B+ with my last proposal, I will add a note that 3B+ is not supported.

If you can get it to work, though, I will add a note how to change the config.

**Comment by canique** [comment]
> I'm also waiting to see how the low energy contest goes, definitely want to work with you on some potential versions to help with rain gauge with hall sensor :-)

I'm right now working on the firmware of the pulse counter (which can be used with a rain gauge). Probably tomorrow I'll make a video "Canique Ambience with temperature/humidity sensor and pulse counter" showing the quiescent current consumption via a 1.8V laboratory power supply. If everything is as expected, total consumption shoule be ~1 µA.

**Comment by earlthesquirrel** [comment]
I'll play with the 3B+ after I get the 3B working....(and try out your latest suggestion).  Want to get the sensor reporting first.
RE: VIdeo
That sounds awesome, let me know when and where it's posted... I'll check it out!

**Comment by earlthesquirrel** [comment]
Let me know when or how I can get one of the new boards so I can start working with you on the rain gauge. :-)

I'll close this issue for now, since changing the psi resolved the issues.

**Comment by canique** [comment]
> I'm also waiting to see how the low energy contest goes

new videos:
https://hackaday.io/project/186949-canique-ambience/log/217102-current-consumption-of-canique-ambience-with-pulse-counter
