### ISSUE TITLE
Didn't get MQTT user and password with Hat

### ISSUE THREAD

**Issue by earlthesquirrel** [canique/gateway#3]
I haven't found the MQTT user/password in with what I received.
The install says : 
            Setup connection between your mosquitto broker and Canique Cloud (optional)
            Enter in a terminal on your Raspberry Pi, replacing MQTT_USER and MQTT_PASSWORD with your own user
            and password that you got with the hat
            canique-setup-mosquitto-bridge MQTT_USER MQTT_PASSWORD
            (You can skip this step if you do not want to use the Canique Cloud. Then your data will stay local.)

I got a sticker with the sensor but don't see anything for the hat.

**Comment by canique** [comment]
Hello,

Please check again (it's there 100%). There is a white paper (format A4) folded twice in your cardbox.
It's not a sticker, it's a normal sheet of paper. There you will find the password for this step, and for the login.

**Comment by earlthesquirrel** [comment]
Ok, I found it minutes before it went into the trash..... it had gotten stuck in box... so got lucky!  Thanks for describing what to look for!

**Comment by canique** [comment]
You're welcome.
Even if you hadn't found it, there are ways of assigning new user credentials - so one way or other this would've been solved.
