### ISSUE TITLE
Should there be some localization?

### ISSUE THREAD

**Issue by earlthesquirrel** [canique/gateway#5]
It would be useful, at least, to have instructions for "tweaking" the website to convert the dialogs, units, number representation, etc. for other locales.

I use deg F, numbers as XX.XX, and English for labels.

**Comment by canique** [comment]
As a starting point: https://github.com/canique/gateway/blob/main/raspberry-pi-radio-hat/local_cockpit.md

**Labels**
Changing text labels in /var/www/canique-gateway/index.html allows changing some labels to other languages.

**Number formatting**
The temperature/humidity formatting cannot be changed easily as of now.

A quick hack for decimal points instead of commas would be to add this code
`<script>
function formatSensorNumber(formattedParts)
{
  return formattedParts.map(({type, value}) => {
    switch (type) {
      case 'decimal': return `.`;
      case 'fraction': return `<span class="smallnum">${value}</span>`;
      default : return value;
    }
  }).reduce((string, part) => string + part);
}
</script>`

to index.html, just before the closing `</head>` tag


**Degrees Fahrenheit**
This is not supported currently. This would need a change in the code with a config variable somewhere.

**Comment by canique** [comment]
There has been some progress on the website https://cockpit.canique.com

There are 2 fields that are parsed now, from Local Storage (viewable in Developer Settings Mode in Chrome Browser e.g. - it's under Application -> Storage -> Local Storage):

1. **locale** this can take the value en-US for example - on next load it will change comma symbols to decimal points
2. **units** Example Value: {"temperature": "F"} - this would convert all temperatures to Fahrenheit

Next step will be to add a little dialog to change this setting more conveniently - right now it can be only set in developer settings.
Note: this setting only affects the local browser, thus it has to be changed on every browser to show an effect.

**Comment by canique** [comment]
![cockpit](https://github.com/canique/gateway/assets/36110883/5a71e3a3-8b39-4d5c-affa-f81a463c93c3)

**Comment by earlthesquirrel** [comment]
Looks great!

Are you going to change the text on the dialog that pops up as well?   See: 

![Screen Shot 2024-03-13 at 1 26 31 PM](https://github.com/canique/gateway/assets/4523243/1228e1fd-75dc-40dd-b8d3-aef6d4767ef2)

**Comment by canique** [comment]
yes, this is also planned.

**Comment by canique** [comment]
Just rolled out an update:

1. The language is determined automatically now from the browser in use. (It can still be overriden with the locale setting mentioned before)
2. When Fahrenheit is selected, the charts are also changed accordingly.
3. Text at various places is adjusted based on the locale setting. English browsers will display english text/date + number formatting by default.

![cockpit canique com_](https://github.com/canique/gateway/assets/36110883/e9d3a91d-c8eb-42cc-9cc9-229639f07af5)

**Comment by earlthesquirrel** [comment]
Looks awesome!  (I moved my sensor around in my house last night and found out that where I put it is a tad too far from the hub -- the rack and walls are a bit too much for the signal to go thru... so I only see cached data.  But all the displays look terrific.  Thanks!

**Comment by canique** [comment]
Latest change:
In the right upper corner you can now see a settings symbol to conveniently change the language.
If "English (US)" is selected, then the temperature will also be displayed in Fahrenheit.

**Comment by earlthesquirrel** [comment]
Wow, the graphs are very nice too!

I just logged in and checked for today, looks awesome. 

One other question -- when will changes like this be available on the canique.local sw?

**Comment by canique** [comment]
> One other question -- when will changes like this be available on the canique.local sw?

In the course of this week, if there are no unforeseen events.

**Comment by canique** [comment]
The update is online now.

Running:
```
sudo apt-get update
sudo apt-get upgrade
```

should get you the locale support on the local canique cockpit. Plus it fixes an issue with mobile chrome browsers asking to do a Google search whenever a phrase is marked.

**Comment by earlthesquirrel** [comment]
Ok, I just did that remotely… but will have to wail til I’m home to check it out…

Earl
