### ISSUE TITLE
canique-setup-mosquitto-bridge needs sudo

### ISSUE THREAD

**Issue by earlthesquirrel** [canique/gateway#6]
Would be helpful to users to know that running 

`canique-setup-mosquitto-bridge  XXXXX XXXXXXXXXXX` 

should be done with sudo. (you can authenticate of course, but sudo would be easier)

Also doing this resets things if you've changed your hostname from what it was initially.

**Comment by canique** [comment]
Fixed in commit 1837d22cc8677e35d77f03a4f5fb19281bc45836
