### ISSUE TITLE
Would like to publish to an additional MQTT broker

### ISSUE THREAD

**Issue by earlthesquirrel** [canique/gateway#7]
Currently, I have another MQTT broker that runs in my local network where all weather data goes (and from which I pick up info for my weather website for my home).    I'd like to incorporate the info from the new temp/humidity sensor.   I'd like to not break your current website (so I can continue to help with your project) nor the cloud website (for the same reason).   Would it be possible to add an additional info for posting to another broker?  Since I only can pull packages, I can't make any suggestions for updates to the code...sorry...

**Comment by canique** [comment]
The easiest way to accomplish this is to setup an additional Mosquitto bridge.

See https://mosquitto.org/man/mosquitto-conf-5.html - "Configuring Bridges"

The connection to the Canique Cloud is done using a Mosquitto bridge. What you can do, is to add a second bridge, that publishes data to your other MQTT broker.

A basic configuration template can be found at /usr/share/canique/mosquitto/canique-bridge.conf
The real configuration (with valid values), that publishes data to the Canique Cloud can be found at /etc/mosquitto/conf.d/canique-bridge.conf
You can copy the configuration file /etc/mosquitto/conf.d/canique-bridge.conf to a new file in the same directory, and adjust basically every line to your needs: turn off SSL, enter client id, username, password, assign a connection name, assign a local clientid, configure which topics to publish...
The local_username and local_password need to stay unchanged. These are used to connect to the local mosquitto broker on the Raspberry Pi.
Make sure to check file permissions/ownership so they are identical to /etc/mosquitto/conf.d/canique-bridge.conf

When finished, restart the mosquitto service.

**Comment by canique** [comment]
Important note: Both local client id, and remote client id must be unique. So do not leave these values unchanged.
Also, the connection name must be unique.

**Comment by earlthesquirrel** [comment]
I've followed your instructions and according to the status it seems to be enabled, but I don't see any data in the remote server...

Still trying to debug... are there any other tools that could show me that messages are begin sent?

**Comment by canique** [comment]
The other MQTT broker is on a different physical machine, correct?
So your setup is:
Raspberry with Canique Hat [sends MQTT data to] -> Other Raspberry


You could try to enable full MQTT logging on both Raspberries.

You could open /etc/mosquitto/conf.d/canique.conf
uncomment the log_type statements by prepepending them with a #
and add `log_type all`

The beginning of the file would then look like this
```
#log_type error
#log_type warning
#log_type notice
log_type all
```
Then you'd need to restart mosquitto: `sudo systemctl restart mosqutto`
And inspect the mosquitto log file: `sudo tail -f /var/log/mosquitto/mosquitto.log`

**Comment by earlthesquirrel** [comment]
So, I've found what looks like the error:

1710265110: Connecting bridge earl-br (172.16.0.4:1883)
1710265110: Bridge canique-earl-br sending CONNECT
1710265110: Client canique-client disconnected: Protocol error.

But no clue yet as to how to configure so protocols align.

**Comment by canique** [comment]
Could you send me the bridge configuration file by mail? Then I can have a look at it.
Or you can post it here, leaving out the passwords...

It could the that you enabled TLS, while this won't work in local networks.
Or that the target broker does not support mqttv50...

**Comment by earlthesquirrel** [comment]
Will do here in a minute.  I'm upgrading the packages on the caniquepi box (didn't look like any mqtt packages changed).  And am going to do similar on my mqttpi box.   But will send config first.

**Comment by earlthesquirrel** [comment]
Here’s the configuration file

connection earl-br
address 172.16.0.4:1883
bridge_capath /etc/ssl/certs

#topic pattern [[[ out | in | both ] qos-level] local-prefix remote-prefix]
topic sensors/# out 1 "" canique/ #publish sensor measurements to cloud
#topic gw/# out 1 "" canique/ #publish gw disk stats, local IP, firmware revision to cloud
#topic alarms/# out 1 "" canique/ #publish triggered alarms to cloud
topic req/# in 1 "" canique/  #receive commands from {username}/req and publish them in req/
topic sensors/+/+/label in 1 "" canique/ #receive label change commands

notifications true
#notifications_local_only true #does not work
#notification_topic c9834/connection/cnq-gw1-br/state

bridge_protocol_version mqttv50
bridge_insecure true
bridge_tls_version tlsv1.3
cleansession false

#use connection name + hostname by default
remote_clientid canique-earl-br
remote_username canique
remote_password xxxx

# login to local broker
local_clientid canique-client
local_username remote-bridge
local_password xxxx

**Comment by canique** [comment]
Try to comment out bridge_capath to disable TLS.

**Comment by earlthesquirrel** [comment]
That was it!   I thought just setting bridge-insecure to true would have done it.

**Comment by earlthesquirrel** [comment]
In the message, btw, I see:
{"ts": 1710266657501, "sid": 359506, "hdt": 34.35, "aH": 8.14, "tmp": 25.52, "rssi": -79}

ts = timestamp
sid = id
hdt =??
aH = Average Humidity?
tmp = Temp in C
rssi = signal rssi.

What is hdt and am I right on average humidity?

**Comment by canique** [comment]
> That was it! I thought just setting bridge-insecure to true would have done it.

I know. I thought exactly the same :) But looked it up in the mosquitto docs then...

aH is absolute humidity.
hdt is relative humidity. It should be rH but for legacy purposes it's still hdt.
sid = sensor id

**Comment by canique** [comment]
Bridge working -> I'm closing the issue.
